added parameters to gpg to verify signature with clock not yet set

diff --git a/src/sbin/init_overlay_second b/src/sbin/init_overlay_second
--- a/src/sbin/init_overlay_second
+++ b/src/sbin/init_overlay_second
@@ -50,7 +50,7 @@ if [ "$DOUPDATE" -eq 1 ] && ! [ -z "$UPFILE" ]
 then
         echo "Applying update"
 	touch /home/pi/doreset
-        CLEAR_UPDATE_FILE=true DOVERIFYSIG=false coderbot_update $UPFILE || fail "ERROR while updating"
+        CLEAR_UPDATE_FILE=true coderbot_update $UPFILE || fail "ERROR while updating"
 fi
 
 #mount root read only
