added tests, fix some errors

diff --git a/src/sbin/merge_overlay b/src/sbin/merge_overlay
--- a/src/sbin/merge_overlay
+++ b/src/sbin/merge_overlay
@@ -15,26 +15,37 @@ fail(){
 
 [[ $1 == "-h" || $1 == "--help" ]] && usage
 
-CONF=/etc/coderbot/init_overlay.conf
-source $CONF ||  fail "ERROR: file not found CONF_FILE: $CONF"
+CONF=${CONF:-/etc/coderbot/init_overlay.conf}
+source $CONF #||  fail "ERROR: file not found CONF_FILE: $CONF"
 
 OVERMPOINT=${OVERMPOINT:-$1}
 ROMMPOINT=${ROMMPOINT:-$2}
 REOPTS="rw,remount,rw"
+UPPERDIR=${UPPERDIR:-upper}
 
 [ -d $OVERMPOINT ] || fail "ERROR: OVERMPOINT $OVERMPOINT directory not faound"
 [ -d $ROMMPOINT ] || fail "ERROR: ROMMPOINT $ROMMPOINT directory not faound"
 
 mount -o $REOPTS $ROMMPOINT || fail "ERROR: can't remount $ROMMPOINT rw"
 
-cd $OVERMPOINT
+cd "$OVERMPOINT/$UPPERDIR" || fail "ERROR: can't cd to $OVERMPOINT/$UPPERDIR, maybe not exists"
 REMOVED=`find . -perm 000 -type c -exec ls -lb {} \; | perl -lane 'if($F[4] == "0" && $F[5] == "0"){$out=join(" ", @F[9..$#F]); $out =~ s/^\.\///; print $out;}'`
-while read line
-do
-	rm -rf "$ROMMPOINT/$line" || fail "ERROR: can't remove $ROMMPOINT/$line"
-done <<< $REMOVED
 
-cp -a $OVERMPOINT/* $ROMMPOINT/ || fail "ERROR in copying files"
+#back to previous dir
+cd - || fail "ERROR: can't cd to previous dir (-)"
+
+if [ -z "$REMOVED" ]
+then
+	echo "Nothing to remove"
+else
+	while read line
+	do
+		rm -rf "$ROMMPOINT/$line" || fail "ERROR: can't remove $ROMMPOINT/$line"
+		rm -rf "${OVERMPOINT}/${UPPERDIR}/$line" || fail "ERROR: can't remove ${OVERMPOINT}/${UPPERDIR}/$line"
+	done <<< $REMOVED
+fi
+
+cp -a "${OVERMPOINT}/${UPPERDIR}/." $ROMMPOINT/ || fail "ERROR in copying files"
 
 echo "Merged ok, now you should clear overlay and backup boot"
 
diff --git a/src/sbin/restore_boot b/src/sbin/restore_boot
--- a/src/sbin/restore_boot
+++ b/src/sbin/restore_boot
@@ -4,18 +4,18 @@
 #
 
 usage() {
-	echo "restore_boot [BACKUPFILE] [SIGNATURE] [DEVICE] [MOUNTPOINT] [KEYRING] [LABEL]"
+	echo "restore_boot [BACKUPFILE] [DEVICE] [MOUNTPOINT] [LABEL]"
 	echo "restore boot partition from a backup, verifying the signature if present"
 	exit 2
 }
 
-MOUNTPOINT=${4:-/boot}
+MOUNTPOINT=${3:-/boot}
 BACKUPFILE=${1:-/etc/coderbot/boot.tar.xz}
-BACKUPSIG=${2:-/etc/coderbot/boot.sig}
-KEYRING=${5:-/etc/coderbot/coderbot.pub}
-DEVICE=${3:-/dev/mmcblk0p1}
-LABEL=${6:-boot}
-FAT_SIZE=32
+BACKUPSIG=${BACKUPSIG:-/etc/coderbot/boot.sig}
+KEYRING=${KEYRING:-/etc/coderbot/coderbot.pub}
+DEVICE=${2:-/dev/mmcblk0p1}
+LABEL=${4:-BOOT}
+FAT_SIZE=${FAT_SIZE:-32}
 
 fail(){
 	echo $1
@@ -39,8 +39,8 @@ do_restore(){
 }
 
 [ -f $BACKUPFILE ] || fail "ERROR: $BACKUPFILE File not Found"
-[ -f $BACKUPSIG ] || fail "ERROR: $BACKUPSIG File not Found"
-[ -f $KEYRING ] || fail "ERROR: $KEYRING File not Found"
+#[ -f $BACKUPSIG ] || fail "ERROR: $BACKUPSIG File not Found"
+#[ -f $KEYRING ] || fail "ERROR: $KEYRING File not Found"
 
 #verify only if signature is present
 [ -f $BACKUPSIG ] && verify
