fix #3

diff --git a/src/sbin/merge_overlay b/src/sbin/merge_overlay
--- a/src/sbin/merge_overlay
+++ b/src/sbin/merge_overlay
@@ -19,12 +19,12 @@ CONF=${CONF:-/etc/coderbot/init_overlay.conf}
 source $CONF #||  fail "ERROR: file not found CONF_FILE: $CONF"
 
 OVERMPOINT=${OVERMPOINT:-$1}
-ROMMPOINT=${ROMMPOINT:-$2}
+ROMMPOINT=/
 REOPTS="rw,remount,rw"
 UPPERDIR=${UPPERDIR:-upper}
 
-[ -d $OVERMPOINT ] || fail "ERROR: OVERMPOINT $OVERMPOINT directory not faound"
-[ -d $ROMMPOINT ] || fail "ERROR: ROMMPOINT $ROMMPOINT directory not faound"
+[ -d $OVERMPOINT ] || fail "ERROR: OVERMPOINT $OVERMPOINT directory not found"
+[ -d $ROMMPOINT ] || fail "ERROR: ROMMPOINT $ROMMPOINT directory not found"
 
 mount -o $REOPTS $ROMMPOINT || fail "ERROR: can't remount $ROMMPOINT rw"
 
@@ -35,6 +35,7 @@ OPAQUE=`getfattr -dm- -R . | perl -le '$lastfile=""; while(<>){if($_ =~ m/^#.*fi
 #back to previous dir
 cd - || fail "ERROR: can't cd to previous dir (-)"
 
+echo "Removing deleted files"
 if [ -z "$REMOVED" ]
 then
 	echo "Nothing to remove"
@@ -46,6 +47,7 @@ else
 	done <<< $REMOVED
 fi
 
+echo "Removing opaque files"
 if [ -z "$OPAQUE" ]
 then
 	echo "No opaque to remove"
@@ -55,6 +57,8 @@ else
 		rm -rf "$ROMMPOINT/$oline" || fail "ERROR: can't remove $ROMMPOINT/$oline"
 	done <<< $OPAQUE
 fi
+
+echo "Copying files from overlay to lower fs"
 
 cp -a "${OVERMPOINT}/${UPPERDIR}/." $ROMMPOINT/ || fail "ERROR in copying files"
 
